### ISSUE TITLE
Create custom AlertManager alert for server reboots

### ISSUE THREAD

**Issue by StevenBarre** [bcgov/developer-experience#5557]
**Describe the issue**
Sometimes a server can reboot and come back up before any other alerts get triggered. Create an alert for "uptime less than 30 min" or something to detect and alert on-call if a node reboots.

**What is the Value/Impact?**
Improved monitoring

**What is the plan? How will this get completed?**
Create a custom alertmanager alert

**Identify any dependencies**
None

**Definition of done**
Tested in lab
Deployed to all prod clusters

**Comment by StevenBarre** [comment]
https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/monitoring/managing-alerts#modifying-core-platform-alerting-rules_managing-alerts-as-an-administrator

```yaml
apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: advsol-alert-rules
  namespace: openshift-monitoring
spec:
  groups:
  - name: advsol-alerts
    rules:
    - alert: NodeRestart
      annotations:
        description: Node {{ $labels.instance }} has restarted.
        summary: Node has restarted.
      expr: |
        (node_time_seconds - node_boot_time_seconds) < 1800
      for: 5m
      labels:
        severity: critical
```
